// Actions
export const ACTION_SEARCH_PLAYER = 'ACTION_SEARCH_PLAYER';
export const ACTION_GET_PROFILE = 'ACTION_GET_PROFILE';
export const ACTION_GET_CHARACTER = 'ACTION_GET_CHARACTER';
export const ACTION_GET_HISTORICAL_STATS = 'ACTION_GET_HISTORICAL_STATS';
export const ACTION_GET_ACCOUNT_HISTORICAL_STATS = 'ACTION_GET_ACCOUNT_HISTORICAL_STATS';
