// Actions
export const ACTION_STATS_FETCH_BEGIN = 'ACTION_STATS_FETCH_BEGIN';
export const ACTION_STATS_FETCH_DONE = 'ACTION_STATS_FETCH_DONE';
export const ACTION_STATS_UPDATE_INPUT = 'ACTION_STATS_UPDATE_INPUT';
export const ACTION_STATS_FETCH_ACCOUNT = 'ACTION_STATS_FETCH_ACCOUNT';
export const ACTION_STATS_GET_PROFILE = 'ACTION_STATS_GET_PROFILE';
export const ACTION_STATS_GET_CHARACTER = 'ACTION_STATS_GET_CHARACTER';
export const ACTION_STATS_GET_HISTORICAL_STATS = 'ACTION_STATS_GET_HISTORICAL_STATS';
export const ACTION_STATS_GET_ACCOUNT_HISTORICAL_STATS = 'ACTION_STATS_GET_ACCOUNT_HISTORICAL_STATS';

// Request Type
export const REQUEST_TYPE_ACCOUNT = 'REQUEST_TYPE_ACCOUNT';
export const REQUEST_TYPE_CHARACTER = 'REQUEST_TYPE_CHARACTER';
export const REQUEST_TYPE_PROFILE = 'REQUEST_TYPE_PROFILE';

// Text
export const SUCCESS = 'Success';
