// Actions
export const ACTION_STATS_FETCH_BEGIN = 'ACTION_STATS_FETCH_BEGIN';
export const ACTION_STATS_FETCH_DONE = 'ACTION_STATS_FETCH_DONE';
export const ACTION_STATS_UPDATE_INPUT = 'ACTION_STATS_UPDATE_INPUT';
export const ACTION_STATS_FETCH_ACCOUNT = 'ACTION_STATS_FETCH_ACCOUNT';
export const ACTION_STATS_FETCH_PROFILE = 'ACTION_STATS_FETCH_PROFILE';
export const ACTION_STATS_FETCH_CHARACTER = 'ACTION_STATS_FETCH_CHARACTER';
export const ACTION_STATS_FETCH_STATS = 'ACTION_STATS_FETCH_STATS';

// Request Type
export const REQUEST_TYPE_ACCOUNT = 'REQUEST_TYPE_ACCOUNT';
export const REQUEST_TYPE_CHARACTER = 'REQUEST_TYPE_CHARACTER';
export const REQUEST_TYPE_PROFILE = 'REQUEST_TYPE_PROFILE';
export const REQUEST_TYPE_STATS = 'REQUEST_TYPE_STATS';

// Text
export const SUCCESS = 'Success';
